config/routes.rb
Rails.application.routes.draw do
  root "entries#index"

  devise_for :users

  authenticate :user, -> (user) { user.admin? } do
    mount Motor::Admin => '/admin'
  end

  resources :entries do
    member do
      post 'upvote', to: 'votes#upvote'
    end
    resources :comments
  end

  resources :tags

  get 'random', to: 'entries#random'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.admin?
      can :manage, :all
      can :read, Motor::Admin
    else
      can :read, Entry
      can :create, Entry if user.persisted?
      can :update, Entry, user_id: user.id
      can :destroy, Entry, user_id: user.id
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
  belongs_to :user
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :taggings, dependent: :delete_all
  has_many :tags, through: :taggings
  has_many :votes, dependent: :delete_all

  has_rich_text :content

  enum status: %i[ drafted published ]

  scope :recent, -> { order(created_at: :desc).limit(25) }

  validates_presence_of :title

  def drafted
    Entry.where(status: 0)
  end

  def published
    Entry.where(status: 1)
  end
  def upvotes_count
    votes.count
  end

end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :delete_all
  has_many :entries, through: :taggings
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :tag, dependent: :delete
  belongs_to :entry, dependent: :delete
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :set_default_admin

  has_many :entries
  has_many :comments
  has_many :votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  paginates_per 50

  private
  def set_default_admin
    self.admin = (email == 'codepunk@qq.com')
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :entry

  validates :user_id, uniqueness: { scope: :entry_id, message: 'has already voted on this entry' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_entry
  before_action :authenticate_user!

  # POST /comments or /comments.json
  def create
    @comment = @entry.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!

    redirect_to @entry
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment = @entry.comments.find(params[:id])
    @comment.destroy!

    redirect_to @entry
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:entry_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create edit update destroy ]

  # GET /entries or /entries.json
  def index
    if params[:search]
      @entries = Entry.where("title LIKE ?", "%#{params[:search]}%").page params[:page]
    else
      @entries = Entry.published.reverse_order.page params[:page]
    end
  end

  # GET /entries/1 or /entries/1.json
  def show
    @comments = @entry.comments.page(params[:page]).per(50)
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    authorize! :update, @entry
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def random
    @entry = Entry.order("RANDOM()").first
    redirect_to @entry
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.published.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:title, :content, :status)
    end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create edit update destroy]

  # GET /tags or /tags.json
  def index
    @tags = Tag.order(:id).page params[:page]
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.fetch(:tag, {})
    end
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  before_action :set_entry
  before_action :authenticate_user!

  def upvote
    existing_vote = current_user.votes.find_by(entry_id: @entry.id)

    # 判断是否已经投票
    if existing_vote
      existing_vote.destroy
    else
      Vote.create(user: current_user, entry: @entry)
    end
    redirect_to @entry
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_page_title(page_title="")
    base_title = "梗多多"
    page_title.empty? ? base_title : page_title + ' - ' + base_title
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong><%= comment.user.name %>:</strong>
    <%= comment.content %>
  </p>

  <% if can? [:destroy], comment %>
    <%= button_to "删除评论", entry_comment_path(comment.entry, comment), class: "button", method: :delete, data: { turbo_confirm: "你确定要删除吗?"} %>
  <% end %>
</div>

app/views/comments/_new.html.erb
<%= form_with(model: [entry, Comment.new]) do |form| %>
  <div>
    <%= form.label "评论", style: "display: block" %>
    <%= form.text_area :content, rows: "3" %>
  </div>

  <div>
    <%= form.submit "留下评论" %>
    <%= link_to "返回词条", entries_path, class: "button" %>
  </div>
<% end %>

app/views/entries/_comments.html.erb
<h3>评论区</h3>

<div id="comments">
  <%= render @comments %>

  <%= paginate @comments %>
</div>

<%= render "comments/new", entry: entry %>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">

  <% if action_name == "index" %>
    <%= link_to entry do %>
      <p><%= entry.title %></p>
    <% end %>

    <p><%= entry.content %></p>

    <p><%= render "entries/tags", entry: entry %></p>

  <% else %>

    <h2><%= entry.title %></h2>

    <% if entry.content.present? %>
      <p><%= entry.content %></p>
    <% end %>

    <p><%= render "entries/tags", entry: entry %></p>
  <% end %>

</div>
<div class="buttons">
  <%= link_to "点赞 #{ entry.votes.count }", upvote_entry_path(entry), class: "button", data: { turbo_method: :post } %>

  <% if can? [:update, :destroy], entry %>
    <%= link_to "编辑词条", edit_entry_path(entry), class: "button" %>
    <%= button_to "删除词条", entry, class: "button", method: :delete, data: { turbo_confirm: "你确定要删除吗?"} %>
  <% end %>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :标题, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :内容, style: "display: block" %>
    <%= form.rich_text_area :content %>

  </div>

  <div>
    <%= form.label :状态, style: "display: block" %>
    <%= form.radio_button :status, "drafted" %>
    <%= form.label "drafted", "草稿" %>
    <%= form.radio_button :status, "published" %>
    <%= form.label "published", "发布" %>
  </div>

  <div class="buttons">
    <%= form.submit "提交", class: "button" %>
    <%= link_to "显示词条", entry, class: "button" %>
    <%= link_to "返回词条", entries_path, class: "button" %>
  </div>
<% end %>

app/views/entries/_tags.html.erb
<strong>标签:</strong>
<% entry.tags.each do |tag| %>
  <%= link_to tag.title, tag %>
<% end %>

app/views/entries/edit.html.erb
<% content_for :page_title, "编辑词条" %>

<h1>编辑词条</h1>

<%= render "form", entry: @entry %>

<br>

app/views/entries/index.html.erb
<% content_for :page_title, "首页" %>

<h1>词条</h1>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
  <% end %>
</div>
<br />

<%= paginate @entries %>

<% if can? :create, Entry %>
  <br/>
  <%= link_to "新增词条", new_entry_path, class: "button" %>
<% end %>

app/views/entries/new.html.erb
<% content_for :page_title, "新增词条" %>

<h1>新增词条</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "返回词条", entries_path %>
</div>

app/views/entries/show.html.erb
<% content_for :page_title, @entry.title %>

<%= render @entry %>

<%= render "entries/comments", entry: @entry %>

app/views/layouts/_footer.html.erb
<% unless %w[ sessions registrations passwords ].include? controller_name %>
  <footer>
    <p>© 2017–2023 梗多多</p>
  </footer>
<%  end %>

app/views/layouts/_header.html.erb
<% unless %w[ sessions registrations passwords ].include? controller_name %>
  <header>
    <nav>
      <%= link_to "首页", root_path %>

      <%= link_to "随机", random_path %>

      <%= link_to "标签", tags_path %>

      <% if user_signed_in? %>
        <%= link_to current_user.name, edit_user_registration_path %>
        <% if current_user.admin? %>
          <%= link_to "后台", "/admin" %>
        <% end %>
        <%= link_to "退出", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "登录", new_user_session_path %>
      <% end %>
    </nav>
    <h1>梗多多</h1>
    <p>互联网🏄指南</p>
    <%= form_with(url: entries_path, method: "get") do |form| %>
      <%= form.text_field :search, placeholder: "搜索..." %>
      <%= form.submit "搜索" %>
    <% end %>
  </header>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_page_title(yield(:page_title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="欢迎来到梗多多，互联网冲浪指南">
  <meta name="keywords" content="梗多多, 梗, 多多, 互联网, 冲浪, 指南">
  <meta property="og:title" content="<%= yield(:page_title) %>">
  <meta property="og:description" content="欢迎来到梗多多，互联网冲浪指南">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>

<%= render "layouts/header" %>

<main>
  <%= yield %>
</main>

<%= render "layouts/footer" %>

</body>
</html>

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "标题", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label "描述", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="buttons">
    <%= form.submit "提交", class: "button" %>
    <%= link_to "返回标签", tags_path, class: "button" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <%= link_to tag do %>
    <h3>
      <%= tag.title %>
    </h3>
  <% end %>
  <p>
    <%= tag.description %>
  </p>

  <% if action_name == "show" %>
    <p>
      <strong>词条数:</strong>
      <%= tag.entries.count %>
    </p>
  <% end %>
</div>

<div class="buttons">
  <% if can? [:update, :destroy], tag %>
    <%= link_to "编辑标签", edit_tag_path(tag), class: "button" %>
    <%= link_to "删除标签", tag, class: "button", data: { turbo_method: :delete } %>
    <% if action_name == "show" %>
      <%= link_to "返回标签", tags_path, class: "button" %>
    <% end %>
  <% else %>
    <% if action_name == "show" %>
      <%= link_to "返回标签", tags_path, class: "button" %>
    <% end %>
  <% end %>
</div>

app/views/tags/edit.html.erb
<% content_for :page_title, "编辑标签" %>

<h1>编辑标签</h1>

<%= render "form", tag: @tag %>

<br>

<div class="buttons">
  <%= link_to "显示标签", @tag, class: "button" %>
  <%= link_to "返回标签", tags_path, class: "button" %>
</div>

app/views/tags/index.html.erb
<% content_for :page_title, "标签" %>

<h1>标签</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>

  <% end %>
</div>

<%= paginate @tags %>

<% if can? :create, Tag %>
  <br/>
  <%= link_to "新增标签", new_tag_path, class: "button" %>
<% end %>

app/views/tags/new.html.erb
<% content_for :page_title, "新增标签" %>

<h1>新增标签</h1>

<%= render "form", tag: @tag %>

<br>

app/views/tags/show.html.erb
<% content_for :page_title, @tag.title %>

<%= render @tag %>